name: shareinfo
description: "Build Career with ShareInfo."

publish_to: 'none'

version: 1.0.0+8

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  connectivity_plus: ^5.0.2
  crypto: ^3.0.3
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_info_plus: ^10.0.1
  dio: ^5.4.0
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  figma_squircle: ^0.5.3
  # dio_cookie_manager: ^3.1.1
  encrypt: ^5.0.3
  envied: ^0.5.3
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.7
  go_router: ^13.1.0
  image_picker: ^1.0.7
  injectable: ^2.3.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  lottie: ^2.6.0
  open_file_plus: ^3.4.1+1
  package_info_plus: ^7.0.0
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  responsive_sizer: ^3.2.0
  scrollable_list_tab_scroller: ^1.1.2
  share_plus: ^9.0.0
  shared_preferences: ^2.2.2
  universal_html: ^2.2.4
  url_launcher: ^6.2.4
  youtube_player_iframe: ^5.1.2

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  icons_launcher: ^2.1.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

icons_launcher:
  image_path: "assets/marketing/app-icon-1024.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    windows:
      enable: true
    web:
      enable: true
      image_path: "assets/marketing/app-icon-1024.png"
      favicon_path: "assets/marketing/app-icon-1024.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/marketing/
    - assets/logo/
    - assets/icons/
    - assets/gif/
    - assets/anim/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/google_fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Nunito-ExtraBold.ttf
          weight: 800
    - family: Cascadia
      fonts:
        - asset: assets/google_fonts/Cascadia.ttf
